### ISSUE TITLE
Amélioration de l'application home-control pour la domotique bticino/legrand

### ISSUE THREAD

**Issue by Darkjeje** [alexylem/jarvis-home-control#1]
Bonjour à tous,

Je vous prie de m’excuser pour ce long message qui lie ma présentation et « ma demande »,

Locataire dans un appartement équipé d'une domotique legrand/bticino avec webserveur, j'ai la possibilité grâce à ce matériel d'effectuer différentes opérations par le biais de différents outils :
-   Allumer/éteindre des lumières ou l’ensemble de la maison (fonctionne en partie avec l’appli home contrôle),
-   Obtenir l’état de la lampe (allumée/éteinte),
-   Ouvrir/fermer/arrêter les volets roulants ou de l’ensemble de la maison,
-   Obtenir la température d’une pièce ou de l’ensemble des pièces,
-   Définir une température de déclenchement du chauffage (je n’ai étudier la possibilité de le faire en .php),
-   Obtenir la consommation instantanée en Watt de la maison.

Ces modules qui fonctionnent avec les interrupteurs muraux, fonctionnent aussi avec la tablette numérique fixée a mur, une appli android développée par un autre résident de l’immeuble, un site web créé par mes soins avec l’aide d’internaute et qui communique en .php)

J’ai auparavant installé l’appli Yana dérivé de Sarah v2 mais que j’ai vite abandonné car pour lancer une commandé, il fallait :
- Prendre le smartphone, 
- Le déverrouiller,
- Lancer l’appli Yana,
- Cliquer sur le micro,
- Attendre 1 à 2 seconde son déclenchement,
- Énoncer la commande,
- Fermer l’appli,
- Fermer le téléphone.
  Bref bien plus long que de se lever et appuyer sur l’interrupteur.
  Aussi je n’utilise plus que mon site web, qui a l’avantage d’être multi plateforme vue qu’en html avec un simple navigateur.
  C’est en me demandant si Yana v4 allait enfin se passer d’un PC Windows que je suis tombé sur la vidéo Youtude de Jarvis et me suis lancé dans son installation.

Ce que j’aimerai (et qui n’est surement pas totalement réalisable à ce jour) :
- Que Jarvis soit en attente du mot clef,
- Qu’il soit joignable dans chaque pièce (multi micro ???) pas pour de suite j’imagine,
- Que je puisse lui demander :
   o  D’allumer/éteindre une ou plusieurs lumières et qu’il me réponde que c’est fait que s’il a le retour de la lampe,
   o  Fermer/ouvrir/arrêter un ou plusieurs volets,
   o  La température d’une ou plusieurs pièces,
   o  La température extérieur (météo)
   o  La conso en Watt de l’appart,
   o  D’allumer/éteindre la TV,
   o  D’allumer/éteindre la freebox player Mini 4k,
   o  De lancer/fermer Emby ou Kodi (appli android TV sur la freebox player mini 4k),
   o  De monter/descendre le volume,
   o  De changer de chaîne,
   o  D’avancer rapidement/faire pause/reprendre la lecture/arrêter le film,
- De changer la voix de Jarvis, dans l’idéale j’aimerai extraire tous les cours passages audio ou le Jarvis d’Iron Man parle en français afin de les mettre comme réponse de Jarvis.sh plutôt que l’actuel voix,
- Que Jarvis.sh reconnaisse ma voix et celle de ma copine. Pour le moment, juste afin d’avoir une réponse par nos prénoms, mais pourquoi pas plus (nos paramétrages,… j’ai juste commencé à vous lire sur le sujet).

Bref, beaucoup de chose surement déjà faisable, d’autre réalisable facilement, et enfin d’autre,… arf

A ce jour, j’ai pu commander l’allumage/extinction des lumières avec l’appli home control, mais seulement en donnant 2 fichiers .php, l’un pour allumer, l’autre pour éteindre les lumières. L’action à exécuter et récupérer par le code php get ne fonctionnant pas, mais cela est surement de ma faute (soucis de paramétrage).

Pour les volets, j’ai pensé copier le code des lumières et le mettre dans le même fichier en changeant certaines variables, ce fut un échec.
J’ai alors dupliqué le plugin et j’ai pu monter/descendre les volets mais je ne pouvais plus allumer/éteindre les lumières.
Bref va falloir que je me mettes au codage linux arf,donc si une âme charitable veux m’expliquer/m’aider/me faire jouer les béta testeurs, je suis preneur ;)

Bonne journée à tous,

Jérémy

**Comment by alexylem** [comment]
Bonjour Jérémy, alors la on va pas pouvoir tout faire sur ce ticket. Il faut normalement 1 ticket par demande, et bien sûr il faut qu'il soit sur le bon repo. La tu es sur le repo du plugin `home-control` donc je vais te répondre pour les demandes à ce sujet.
Ce plugin est pour envoyer des requêtes `http`, c'est ce que tu fais? ou tu a modifié le plugin pour exécuter du code php? Tu peux partager ton fichier de config stp?

Pour la plupart de tes autres demandes elles ont déjà été discutées, je te conseille d'utiliser la recherche sur le repo https://github.com/alexylem/jarvis

**Comment by Darkjeje** [comment]
Merci Alex pour ton retour.
Je te rassure, je ne comptais pas avoir des réponses à l'ensemble de mes demandes, mais je voulais faire une présentation de ce que je comptais faire.

Pour le plugin, oui le but est d'envoyer des requêtes http vers mes fichiers .php déjà créé.

Voici le fichier conf actuel : 
`pg_hc_turnon_url="http://192.168.1.6/Jarvis/Allumage_lampe.php?device=[ADDRESS]"
pg_hc_turnoff_url="http://192.168.1.6/Jarvis/Eteindre_lampe.php?device=[ADDRESS]"
pg_hc_config='{ "devices":[
    { "name": "MAISON", "address": "0"},
    { "name": "COULOIR", "address": "11"},
    { "name": "BUREAU", "address": "22"},
    { "name": "CHAMBRE", "address": "81"},
    { "name": "SALON", "address": "17"},
    { "name": "TOILETTE", "address": "31"},
    { "name": "SALLE_DE_BAIN_PLAFONNIER", "address": "33"},
    { "name": "SALLE_DE_BAIN_MIROIR", "address": "34"},
    { "name": "CUISINE_PLAFONNIER", "address": "15"},
    { "name": "CUISINE_PLAN_DE_TRAVAIL", "address": "16"}

]}'`

**Comment by Darkjeje** [comment]
Bon j'ai finalement pu faire fonctionner mes lumières avec ton script, je ne sais pas pourquoi récupéré action, ne fonctionnait pas et m'avait obligé à créer 2 fichiers .php différents pour allumer et éteindre, mais en tout cas maintenant ça fonctionne.

Voici donc mon fichier conf. pour la lumière : 
`pg_hc_turnon_url="http://192.168.1.6/Jarvis/Commande_lampe.php?action=1&device=[ADDRESS]"
pg_hc_turnoff_url="http://192.168.1.6/Jarvis/Commande_lampe.php?action=0&device=[ADDRESS]"
pg_hc_config='{ "devices":[
    { "name": "MAISON", "address": "0"},
    { "name": "COULOIR", "address": "11"},
    { "name": "BUREAU", "address": "22"},
    { "name": "CHAMBRE", "address": "81"},
    { "name": "SALON", "address": "17"},
    { "name": "TOILETTE", "address": "31"},
    { "name": "SALLE DE BAIN", "address": "33"},
    { "name": "MIROIR", "address": "14"},
    { "name": "CUISINE", "address": "15"},
    { "name": "PLAN DE TRAVAIL", "address": "16"}

]}'

Et celui des volets :
`pg_hc_open_url="http://192.168.1.6/Jarvis/Commande_volet.php?action=1&device=[ADDRESS]"
pg_hc_close_url="http://192.168.1.6/Jarvis/Commande_volet.php?action=2&device=[ADDRESS]"
pg_hc_stop_url="http://192.168.1.6/Jarvis/Commande_volet.php?action=0&device=[ADDRESS]"
pg_hc_config='{ "devices":[
    { "name": "MAISON", "address": "5"},
    { "name": "BUREAU", "address": "52"},
    { "name": "CHAMBRE", "address": "51"},
    { "name": "BALCON", "address": "58"},
    { "name": "SALON", "address": "57"}

]}'
`

Et voici le fichier function.sh qui est à mon avis totalement faut car je ne connais pas ce langage :

`#!/bin/bash

# Here you can create functions which will be available from the commands file

# You can also use here user variables defined in your config file

pg_jc_do () {
    # $1: action [open|close|stop]
    # $2: received order
    [ "$1" == "close" ] && local url="$pg_hc_close_url" || local url="$pg_hc_open_url" || local url="$pg_hc_stop_url"

```
local -r order="$(jv_sanitize "$2")"
while read device; do
    local sdevice="$(jv_sanitize "$device" ".*")"
    if [[ "$order" =~ .*$sdevice.* ]]; then
        local address="$(echo $pg_hc_config | jq -r ".devices[] | select(.name==\"$device\") | .address")"
        jv_curl "${url//\[ADDRESS\]/$address}"
        return $?
    fi
done <<< "$(echo $pg_hc_config | jq -r '.devices[].name')"
jv_error "ERROR: no device maching $2"
return 1
```

}
`

Si jamais tu peux essayer de m'expliquer ce serait super ;)

**Comment by Darkjeje** [comment]
Bon j'ai réussi à faire fonctionner les volets et les lumières avec le code ci-dessous.
Mais j'ai des erreurs car j'ai plusieurs fois le même nom,... Il faudrait donc coder différemment pour ne plus avoir ce problème car changer les noms ne seraient pas pratique du tout.
Config.sh : 
`pg_hc_turnon_url="http://192.168.1.6/Jarvis/Commande_lampe.php?action=1&device=[ADDRESS]"
pg_hc_turnoff_url="http://192.168.1.6/Jarvis/Commande_lampe.php?action=0&device=[ADDRESS]"
pg_hc_open_url="http://192.168.1.6/Jarvis/Commande_volet.php?action=1&device=[ADDRESS]"
pg_hc_close_url="http://192.168.1.6/Jarvis/Commande_volet.php?action=2&device=[ADDRESS]"
pg_hc_stop_url="http://192.168.1.6/Jarvis/Commande_volet.php?action=0&device=[ADDRESS]"
pg_hc_config='{ "devices":[
    { "name": "MAISON", "address": "0"},
    { "name": "COULOIR", "address": "11"},
    { "name": "BUREAU", "address": "22"},
    { "name": "CHAMBRE", "address": "81"},
    { "name": "SALON", "address": "17"},
    { "name": "TOILETTE", "address": "31"},
    { "name": "SALLE DE BAIN", "address": "33"},
    { "name": "MIROIR", "address": "14"},
    { "name": "CUISINE", "address": "15"},
    { "name": "PLAN DE TRAVAIL", "address": "16"},
    { "name": "MAISON", "address": "5"},
    { "name": "BUREAU", "address": "52"},
    { "name": "CHAMBRE", "address": "51"},
    { "name": "BALCON", "address": "58"},
    { "name": "SALON", "address": "57"}
]}'`

Command : 
`*ALLUME*==pg_jc_turn on "$order" && say "VoilÃ "
*ETEIN*==pg_jc_turn off "$order" && say "VoilÃ "
*OUVRE*==pg_jc_do open "$order" && say "VoilÃ "
*FERME*==pg_jc_do close "$order" && say "VoilÃ "
*ARRETE*==pg_jc_do stop "$order" && say "VoilÃ "`

Functions.sh : 
`#!/bin/bash

pg_jc_turn () {
    # $1: action [on|off]
    # $2: received order
    [ "$1" == "off" ] && local url="$pg_hc_turnoff_url" || local url="$pg_hc_turnon_url"
    local -r order="$(jv_sanitize "$2")"
    while read device; do
        local sdevice="$(jv_sanitize "$device" "._")"
        if [[ "$order" =~ ._$sdevice.\* ]]; then
            local address="$(echo $pg_hc_config | jq -r ".devices[] | select(.name==\"$device\") | .address")"
            jv_curl "${url//[ADDRESS]/$address}"
            return $?
        fi
    done <<< "$(echo $pg_hc_config | jq -r '.devices[].name')"
    jv_error "ERROR: no device maching $2"
    return 1
}

pg_jc_do () {
    # $1: action [open|close]
    # $2: received order
    [ "$1" == "close" ] && local url="$pg_hc_close_url" || local url="$pg_hc_open_url"

```
local -r order="$(jv_sanitize "$2")"
while read device; do
    local sdevice="$(jv_sanitize "$device" ".*")"
    if [[ "$order" =~ .*$sdevice.* ]]; then
        local address="$(echo $pg_hc_config | jq -r ".devices[] | select(.name==\"$device\") | .address")"
        jv_curl "${url//\[ADDRESS\]/$address}"
        return $?
    fi
done <<< "$(echo $pg_hc_config | jq -r '.devices[].name')"
jv_error "ERROR: no device maching $2"
return 1
```

}`

Merci pour votre aide !!!

**Comment by alexylem** [comment]
Ok tu utilises bien le plugin, et effectivement de base il fonctionne pour les commandes "allume" et "éteins" mais pas "ouvre/ferme/arrête".
T'es pas trop censé modifier le fichier `functions.sh` ni `commands` d'ailleurs. Le plus simple est que je modifie le plugin pour supporter ces nouveaux "verbes".
Si t'es d'accord je fais ca ce week-end.

**Comment by Darkjeje** [comment]
Avec plaisir, si tu as besoin d'aide, pour tester,... n'hésite pas.
J'ai changé le fichier config afin d'intégrer la notion de volet et de lumière.
`pg_hc_turnon_url="http://192.168.1.6/Jarvis/Commande_lampe.php?action=1&device=[ADDRESS]"
pg_hc_turnoff_url="http://192.168.1.6/Jarvis/Commande_lampe.php?action=0&device=[ADDRESS]"
pg_hc_open_url="http://192.168.1.6/Jarvis/Commande_volet.php?action=1&device=[ADDRESS]"
pg_hc_close_url="http://192.168.1.6/Jarvis/Commande_volet.php?action=2&device=[ADDRESS]"
pg_hc_stop_url="http://192.168.1.6/Jarvis/Commande_volet.php?action=0&device=[ADDRESS]"
pg_hc_config='{ "devices":[
    { "name": "LUMIERE MAISON", "address": "0"},
    { "name": "LUMIERE COULOIR", "address": "11"},
    { "name": "LUMIERE BUREAU", "address": "22"},
    { "name": "LUMIERE CHAMBRE", "address": "81"},
    { "name": "LUMIERE SALON", "address": "17"},
    { "name": "LUMIERE TOILETTE", "address": "31"},
    { "name": "LUMIERE SALLE DE BAIN", "address": "33"},
    { "name": "LUMIERE MIROIR", "address": "14"},
    { "name": "LUMIERE CUISINE", "address": "15"},
    { "name": "LUMIERE PLAN DE TRAVAIL", "address": "16"},
    { "name": "VOLET MAISON", "address": "5"},
    { "name": "VOLET BUREAU", "address": "52"},
    { "name": "VOLET CHAMBRE", "address": "51"},
    { "name": "VOLET BALCON", "address": "58"},
    { "name": "VOLET SALON", "address": "57"}
]}'`

**Comment by alexylem** [comment]
Juste par curiosité, je vois que tu passes un paramètres action avec les valeurs 0, 1, 2.
J'essaye de faire en sorte que le plugin soit le plus simple possible.
Est-ce que tu as vraiment besoin d'avoir 3 valeurs? Ton système de domotique a aussi 3 valeurs ou tu peux te contenter de 2 valeurs (une pour allume/ouvrir/démarrer, et une pour éteindre/fermer/arrêter). En gros est-ce que 2 urls suffisent?
Merci 😄

**Comment by Darkjeje** [comment]
Oui j'ai en effet 3 valeurs pour les volets et 2 pour les lampes au niveau de ma domotique.
L'idéal serait d'avoir un plugin spécial domotique bticino qui ne ferait que lancer une page .php en fonction du mot entendu.
Exemple : 
_Allume_ == ordre de lancer la page web .php (action = 1) device (dans la liste à remplir par l'utilisateur)
_ouvre_ == ordre de lancer la page web .php (action = 1) device (dans la liste à remplir par l'utilisateur)
En ne faisant que correspondre un mot avec une page web avec les 2 gets (action et device).
Je me chargerai alors de le tester et de t'envoyer les x pages php. à insérer dans le plugin.
- Commande Lampe
- Commande volet
- Commande température

Si tu as la possibilité de lire le texte écrit dans un fichier html/php par la voix de Jarvis ce serait top. Ca permettrait de lire la température, ou de lire l'état de la lampe.
Exemple : La lumière du salon est-elle éteinte ? --> .php d'interrogation de l'état de la lampe retourne une phrase qui est lu par Jarvis.

Peut-être que tu expliques dans github comment créer tout ça, j'avoue ne pas avoir encore eu le temps de chercher.

**Comment by Darkjeje** [comment]
La 3ème valeur pour les volets est importante pour ouvrir/fermer un volet jusqu'à une certaine hauteur en  demandant à Jarvis d'arrêter l'action d'ouverture/fermeture.

**Comment by alexylem** [comment]
Je me demande si tu as vraiment besoin d'un plugin pour faire tout ca... sache que sans plugin Jarvis permet déjà de faire tout ce dont tu as besoin...
**commands** (Jarvis > Commands)

``` shell
*ALLUME*LAMPE*==jv_curl "http://12.34.56.78/Commande_lampe.php?action=1&device=lampe"
*ETEIN*LAMPE*==jv_curl "http://12.34.56.78/Commande_lampe.php?action=0&device=lampe"
```

Pour faire parler la température,
**commands** (Jarvis > Commands)

``` shell
*TEMPERATURE*SALON*==say "la température est de $(jv_curl "http://12.34.56.78/temperature.php?device=salon") degrés"
```

Si tout ca est nouveau pour toi, je te conseille vivement d'aller faire un tour sur:
http://domotiquefacile.fr/jarvis/content/commands
Lorsque tu seras à l'aise avec tout ca, tu pourras même créer ton propre plugin `bticino` et le partager avec le reste de la communauté Jarvis.
Tiens moi au courant,
Alex.

**Comment by Darkjeje** [comment]
Ah super c'est ça "jv_curl" qu'il me manquait.
Bon ben je vais tester tout ça.
Le codage que tu utilises à un nom que je puisse me rendre sur des sites pour apprendre ?

Merci en tout cas pour tes explications.
Par contre, cela me fait perdre la notion de device si je ne passe plus par le plugin ?

**Comment by alexylem** [comment]
C'est du `bash` (aussi appelé `shell`) tout simplement.
D'ailleurs `jv_curl` est un wrapper Jarvis de `curl` qui est généralement disponible sur la plupart des terminaux Unix. Je conseille d'utiliser `jv_curl` plutôt que `curl` car il permet de débugger facilement (il affiche des logs en mode troubleshooting).
Ex:

``` shell
$> ./jarvis.sh -x "allume lampe" # exécuter directement un ordre
# si ta commande utilise jv_curl, elle va afficher exactement l'URL qu'elle appelle et le message de retour
```

Du coup j'imagine qu'on peut fermer ce ticket?
Plus d'information sur `jv_curl` dans la public API reference:
http://domotiquefacile.fr/jarvis/content/public-api-reference
Alex.
