### ISSUE TITLE
Add extra curl parameters

### ISSUE THREAD

**Issue by wikijm** [alexylem/jarvis-home-control#2]
Hi,

I'm very interested about playing cURL command like this:
`curl "http://[CAMIP]/setSystemMotion" -H "Host: [CAMIP]" -H "Referer: http://[CAMIP]/setSystemMotion" -H "Authorization: Basic [CAMAUTHCODE]" -H "Connection: keep-alive" -H "Upgrade-Insecure-Requests: 1" --data "ReplySuccessPage=motion.htm&ReplyErrorPage=motion.htm&MotionDetectionEnable=1&MotionDetectionScheduleDay=127&MotionDetectionScheduleMode=0&MotionDetectionSensitivity=70&ConfigSystemMotion=Save" >/dev/null 2>&1` (command to disable motion detection on IP camera)

As you can see, I have to use cURL instead of a simple HTTP request, because I have to provide things like "Authorization" or "ReplySuccessPage".

Is it possible with this plugin?
Do I have to create an issue on https://github.com/alexylem/jarvis instead?

Best regards,
@WikiJM

**Comment by alexylem** [comment]
home control is built using `jv_curl` which is a wrapper of `curl`.
So no pb to make it evolve and accept new parameters. Though I have to include this in the plugin.
Could you please narrow your request down to the parameters mandatory for your usage? then I will add them and make them available in the config file.

**Comment by wikijm** [comment]
Thanks for your answer.
Unfortunately, all seems mandatory in my case.

- Host
- Referer
- Authorization
- Connection
- Upgrade-Insecure-Requests
- --data (be aware that '--data' seems to be a parameter which difers to '-H')

You can find more information about my usage here: https://www.developpez.net/forums/d1424172/systemes/hardware/achat-conseils/peripheriques/camera-ip-commandes-url-api-dlink-dcs-932l/#post8858654

**Comment by alexylem** [comment]
Just to better understand your usage of home-control. What would be the order in your case?
```
Allume la webcam?
```
And what will it do? Enable motion detection?

**Comment by wikijm** [comment]
Exactly like on this plugin:
https://github.com/wikijm/jarvis-motiondetectiondlink

The idea is, when I leave the home, to active the motion detection (with a "Lance la détection/Start the detection").
In the same way, when I go back, I just have to say "Arrête la détection/Stop the detection".

**Comment by alexylem** [comment]
Except that home-control plugin only has "Switch on" and "Switch off". Not "Start" and "Stop".
Are you planning to add them too, or make your own commands/plugin?
Just asking to make sure before I modify this plugin.

**Comment by wikijm** [comment]
I try to create to adpatable at any context as much as possible, by using variable like `motiondetectiondlink_cmddisable` on https://github.com/wikijm/jarvis-motiondetectiondlink/blob/master/fr/functions.sh

I'm not against continue to work on my own plugin.

**Comment by alexylem** [comment]
Mmmmh,
Looking into the details, it seems that `data` parameters will be dynamic based on your order.
In the home-control plugin, only the URL (host) is dynamic.
These are the changes I foresee for the config file for your usage:
```shell
pg_hc_turnon_url="http://192.168.1.1/home.php?action=on&device=[ADDRESS]"
pg_hc_turnoff_url="http://192.168.1.1/home.php?action=off&device=[ADDRESS]"
pg_hc_config='{ "devices":[
    { "name": "BEDROOM", "address": "A1"},
    { "name": "LIVING ROOM", "address": "A2"},
    { "name": "BAR", "address": "A3"}
]}'
```
will become something like
```shell
pg_hc_turnon_url="http://192.168.1.1/setSystemMotion"
pg_hc_turnoff_url="http://192.168.1.1/setSystemMotion"
pg_hc_headers='{ "headers":[
    { "Host": "192.168.1.1"},
    { "Referer": "http://192.168.1.1/setSystemMotion"},
    { "Authorization": "Basic 123CAMAUTHCODE456"},
    { "Connection": "keep-alive"},
    { "Upgrade-Insecure-Requests": "1"},
]}'
pg_hc_turnon_data="ReplySuccessPage=motion.htm&ReplyErrorPage=motion.htm&MotionDetectionEnable=1&MotionDetectionScheduleDay=127&MotionDetectionScheduleMode=0&MotionDetectionSensitivity=70&ConfigSystemMotion=Save"
pg_hc_turnoff_data="ReplySuccessPage=motion.htm&ReplyErrorPage=motion.htm&MotionDetectionEnable=0&MotionDetectionScheduleDay=127&ConfigSystemMotion=Save"
pg_hc_config='{ "devices":[
    { "name": "DETECTION", "address": ""}
]}'
```
I'm afraid it will become a bit too complex for lambda user...
At the end if you just want to have those two commands, you'd maybe better to create them manually in your commands file:
```shell
STOP*DETECTION==curl "http://'"$motiondetectiondlink_camip"'/setSystemMotion" -H "Host: '"$motiondetectiondlink_camip"'" -H "Referer: http://'"$motiondetectiondlink_camip"'/setSystemMotion" -H "Authorization: Basic '"$motiondetectiondlink_camauthcode"'" -H "Connection: keep-alive" -H "Upgrade-Insecure-Requests: 1" --data "ReplySuccessPage=motion.htm&ReplyErrorPage=motion.htm&MotionDetectionEnable=0&MotionDetectionScheduleDay=127&ConfigSystemMotion=Save" >/dev/null 2>&1
START*DETECTION==curl "http://'"$motiondetectiondlink_camip"'/setSystemMotion" -H "Host: '"$motiondetectiondlink_camip"'" -H "Referer: http://'"$motiondetectiondlink_camip"'/setSystemMotion" -H "Authorization: Basic '"$motiondetectiondlink_camauthcode"'" -H "Connection: keep-alive" -H "Upgrade-Insecure-Requests: 1" --data "ReplySuccessPage=motion.htm&ReplyErrorPage=motion.htm&MotionDetectionEnable=1&MotionDetectionScheduleDay=127&MotionDetectionScheduleMode=0&MotionDetectionSensitivity=70&ConfigSystemMotion=Save" >/dev/null 2>&1
```
I think it would be much simpler and appropriate to what you want to achieve, what do you think?

**Comment by wikijm** [comment]
I confirm that it seems pretty touchy to use.
I'll try to apply you advices, but if you see any error on my plugin, don't hesitate to create a pull request ;-)

As usual, thanks for your time :-)
